# All notes end with two values, the coordinates of x and y.
# The origin of the coordinates is in the lower left corner of the screen and the unit is percentage
launcher_power_50_40: # eg: x 50%, y 50%
  '65inch':
    do: 1
    ao: [950,985]
  '55inch':
    do: 1
    ao: [950,985]
  '32inch':
    do: 1
    ao: [900,935]

pure_white_50_45:
  '65inch':
    do: 0
    ao: [200,250]
  '55inch':
    do: 0
    ao: [220,350]
  '32inch':
    do: 0
    ao: [150,350]

backlight_off:
  '65inch':
    do: 1
    ao: [ 1000,1010 ]
  '55inch':
    do: 1
    ao: [1000,1010]
  '32inch':
    do: 1
    ao: [950,1010]

launcher_50_40:
  '65inch':
    do: 1
    ao: [600,670]
  '55inch':
    do: 1
    ao: [700,850]
  '32inch':
    do: 1
    ao: [400,800]

netflix_15_70:
  '65inch':
    do: 2
    ao: [ 0,300 ]
  '55inch':
    do: 2
    ao: [0,600]
  '32inch':
    do: 2
    ao: [0,500]

youtube_85_90:
  '65inch':
    do: 0
    ao: [ 0,400 ]
  '55inch':
    do: 0
    ao: [0,550]
  '32inch':
    do: 0
    ao: [0,500]

wifi_scan:
  '55inch':
    do: 0
    ao: [0,650]
  '32inch':
    do: 0
    ao: [0,450]

serial_crt:
  port: /dev/ttyUSB0
  baud: 115200
