# All notes end with two values, the coordinates of x and y.
# The origin of the coordinates is in the lower left corner of the screen and the unit is percentage
home_white:
  '50inch': 163
  '32inch':
    do: 0
    ao: [ 150,350 ]

setting_white:
  '50inch': [ 180,230 ]
  '32inch':
    do: 0
    ao: [ 150,350 ]

color_bar:
  'EcoSave': [140,160]
  'Vivid': [168,196]
  'Sports': [168,195]
  'Movie': [143,172]
  'Normal': [168,194]
  'Store': [168,197]

#color_bar_size:
#  'Auto':
#    do: 0
#    ao: [ 380,395 ]
#  'Direct':
#    do: 0
#    ao: [ 380,395 ]
#  'Normal':
#    do: 0
#    ao: [ 380,395 ]
#  'Stretch':
#    do: 0
#    ao: [ 380,395 ]
#  'Zoom':
#    do: 0
#    ao: [ 380,395 ]
