#light_sensitive_sensor:
#  [
#    "sensor_0": {
#      # do number should be BCM number
#      do: 22,
#      ao: 0x10,
#      status: enable
#    },
#    "sensor_1": {
#      do: 23,
#      ao: 0x11,
#      status: enable
#    },
#    "sensor_2": {
#      do: 24,
#      ao: 0x12,
#      status: enable
#    }
#  ]

connect_type:
  type: telnet
  adb:
    device: "48854121100023837"
  telnet:
    ip: '192.168.50.109'
    #    market 区域 默认填写 sandia  支持列表：sandia,sandia_latam,sandia_hkc,sandia_dvb
    wildcard: sandia


# 信号发射器 相关配置
pattern_generator:
  status: False
  # 目前只支持 8100s
  device: master_8100s
  # 串口连接方式
  connect: serial
  # 串口配置
  serial_setting:
    path: COM7
    baud: 115200


power_crt:
  status: False
  ip: 192.168.50.98


light_sensor:
  status: False

repeat_test: 5

  

