#light_sensitive_sensor:
#  [
#    "sensor_0": {
#      # do number should be BCM number
#      do: 22,
#      ao: 0x10,
#      status: enable
#    },
#    "sensor_1": {
#      do: 23,
#      ao: 0x11,
#      status: enable
#    },
#    "sensor_2": {
#      do: 24,
#      ao: 0x12,
#      status: enable
#    }
#  ]

connect_type:
  type:
  adb:
    device: "48854121100023837"
  telnet:
    ip: '192.168.50.249'


# 信号发射器 相关配置
pattern_generator:
  # 目前只支持 8100s
  device: master_8100s
  # 串口连接方式
  connect: serial
  # 串口配置
  serial_setting:
    path: COM7
    baud: 115200


sensor_board_addr: 0x24

power_crt: 192.168.50.98

repeat_test: 5

  

